ARG RUBY_VERSION=3.3.0
ARG DEBIAN_VERSION=bullseye
FROM public.ecr.aws/docker/library/ruby:${RUBY_VERSION}-slim-${DEBIAN_VERSION} AS ruby-upstream

ARG NODE_MAJOR=22

RUN apt-get update && \
    apt-get install -y curl software-properties-common gnupg2 && \
    curl -fsSL https://deb.nodesource.com/setup_${NODE_MAJOR}.x | bash - && \
    apt-get install -y \
        imagemagick \
        iproute2 \
        libjemalloc2 \
        less \
        postgresql-client \
        tzdata \
        nodejs && \
    apt-get clean

RUN corepack enable

CMD [ "/usr/local/bin/irb" ]
