require "rails_helper"

RSpec.describe "EmailSubscriptions" do
  let(:user) { create(:user) }

  before do
    user.notification_setting.update!(email_digest_periodic: true, email_mention_notifications: true)
  end

  def generate_token(user_id)
    Rails.application.message_verifier(:unsubscribe).generate({
                                                                user_id: user_id,
                                                                email_type: :email_mention_notifications,
                                                                expires_at: 31.days.from_now
                                                              })
  end

  def unsubscribe_with(token)
    public_send(request_method, email_subscriptions_unsubscribe_path(ut: token),
                params: request_method == :post ? { "List-Unsubscribe" => "One-Click" } : {})
  end

  shared_examples "verified unsubscribe payloads" do
    let(:payload) do
      {
        "user_id" => user.id,
        "email_type" => "email_digest_periodic",
        "expires_at" => 31.days.from_now.to_time.getlocal("+02:00").iso8601(3)
      }
    end

    around do |example|
      original = ActionController::Base.allow_forgery_protection
      ActionController::Base.allow_forgery_protection = true
      example.run
    ensure
      ActionController::Base.allow_forgery_protection = original
    end

    it "accepts JSON string keys and an ISO 8601 expiry without changing other subscriptions" do
      original_settings = user.notification_setting.attributes.except("updated_at")
      token = Rails.application.message_verifier(:unsubscribe).generate(payload)

      unsubscribe_with(token)

      expect(response).to have_http_status(:ok)
      expect(user.notification_setting.reload.attributes.except("updated_at"))
        .to eq(original_settings.merge("email_digest_periodic" => false))
      email_name = I18n.t("email_subscriptions_controller.digest_emails", community: Settings::Community.community_name)
      expect(response.body).to include(email_name)
    end

    it "round trips a token generated by the mailer without requiring a session" do
      token = ApplicationMailer.new.generate_unsubscribe_token(user.id, :email_digest_periodic)

      unsubscribe_with(token)

      expect(response).to have_http_status(:ok)
      expect(user.notification_setting.reload.email_digest_periodic).to be(false)
      expect(controller.current_user).to be_nil
    end

    it "accepts a legacy Marshal token containing symbols and a TimeWithZone" do
      secret_generator = Rails.application.message_verifiers.instance_variable_get(:@secret_generator)
      verifier = ActiveSupport::MessageVerifier.new(
        secret_generator.call("unsubscribe"), digest: "SHA1", serializer: Marshal
      )
      token = verifier.generate({ user_id: user.id, email_type: :email_digest_periodic, expires_at: 31.days.from_now })

      unsubscribe_with(token)

      expect(response).to have_http_status(:ok)
      expect(user.notification_setting.reload.email_digest_periodic).to be(false)
    end

    it "changes the token owner's subscription when a different user is signed in" do
      signed_in_user = create(:user)
      signed_in_user.notification_setting.update!(email_digest_periodic: true)
      sign_in signed_in_user
      token = Rails.application.message_verifier(:unsubscribe).generate(payload)

      unsubscribe_with(token)

      expect(user.notification_setting.reload.email_digest_periodic).to be(false)
      expect(signed_in_user.notification_setting.reload.email_digest_periodic).to be(true)
      expect(controller.current_user).to eq(signed_in_user)
    end

    it "allows the same valid link to be used again" do
      token = Rails.application.message_verifier(:unsubscribe).generate(payload)
      2.times { unsubscribe_with(token) }

      expect(response).to have_http_status(:ok)
      expect(user.notification_setting.reload.email_digest_periodic).to be(false)
    end

    it "rejects a modified signature without changing subscriptions" do
      token = Rails.application.message_verifier(:unsubscribe).generate(payload)

      expect { unsubscribe_with("#{token}tampered") }.to raise_error(ActiveRecord::RecordNotFound)
      expect(user.notification_setting.reload.email_digest_periodic).to be(true)
    end

    it "rejects a token at its exact expiry" do
      Timecop.freeze(Time.current.change(usec: 0)) do
        expired_payload = payload.merge("expires_at" => Time.current.iso8601)
        token = Rails.application.message_verifier(:unsubscribe).generate(expired_payload)

        unsubscribe_with(token)

        expect(response.body).to include("Token expired or invalid")
        expect(user.notification_setting.reload.email_digest_periodic).to be(true)
      end
    end

    [nil, "not-a-date", 123, []].each do |expiration|
      it "rejects an invalid expiry #{expiration.inspect} without changing subscriptions" do
        token = Rails.application.message_verifier(:unsubscribe).generate(payload.merge("expires_at" => expiration))

        unsubscribe_with(token)

        expect(response.body).to include("Token expired or invalid")
        expect(user.notification_setting.reload.email_digest_periodic).to be(true)
      end
    end

    %w[user_id email_type expires_at].each do |claim|
      it "rejects a missing #{claim} claim without changing subscriptions" do
        token = Rails.application.message_verifier(:unsubscribe).generate(payload.except(claim))

        unsubscribe_with(token)

        expect(response.body).to include("Token expired or invalid")
        expect(user.notification_setting.reload.email_digest_periodic).to be(true)
      end
    end

    [nil, "not-a-hash", []].each do |malformed_payload|
      it "rejects a non-hash payload #{malformed_payload.inspect}" do
        token = Rails.application.message_verifier(:unsubscribe).generate(malformed_payload)

        unsubscribe_with(token)

        expect(response.body).to include("Token expired or invalid")
        expect(user.notification_setting.reload.email_digest_periodic).to be(true)
      end
    end

    it "rejects unsupported notification attributes" do
      unsupported_payload = payload.merge("email_type" => "welcome_notifications")
      token = Rails.application.message_verifier(:unsubscribe).generate(unsupported_payload)
      original_settings = user.notification_setting.attributes

      unsubscribe_with(token)

      expect(response.body).to include("Token expired or invalid")
      expect(user.notification_setting.reload.attributes).to eq(original_settings)
    end

    it "handles a deleted user as not found" do
      missing_user_payload = payload.merge("user_id" => User.maximum(:id) + 1)
      token = Rails.application.message_verifier(:unsubscribe).generate(missing_user_payload)

      expect { unsubscribe_with(token) }.to raise_error(ActiveRecord::RecordNotFound)
      expect(user.notification_setting.reload.email_digest_periodic).to be(true)
    end
  end

  %i[get post].each do |method|
    describe "#{method.upcase} token compatibility and validation" do
      let(:request_method) { method }

      include_examples "verified unsubscribe payloads"
    end
  end

  describe "GET /email_subscriptions/unsubscribe" do
    it "returns 200 if valid" do
      get email_subscriptions_unsubscribe_url(ut: generate_token(user.id))
      expect(response).to have_http_status(:ok)
    end

    it "returns 200 if token is in legacy Marshal format" do
      secret_generator = Rails.application.message_verifiers.instance_variable_get(:@secret_generator)
      secret = secret_generator.call(:unsubscribe.to_s)
      marshal_verifier = ActiveSupport::MessageVerifier.new(secret, digest: "SHA1", serializer: Marshal)
      legacy_token = marshal_verifier.generate({
                                                 user_id: user.id,
                                                 email_type: "email_mention_notifications",
                                                 expires_at: 31.days.from_now.iso8601
                                               })

      get email_subscriptions_unsubscribe_url(ut: legacy_token)
      expect(response).to have_http_status(:ok)
      user.reload
      expect(user.notification_setting.email_mention_notifications).to be(false)
    end

    it "does unsubscribe the user" do
      get email_subscriptions_unsubscribe_url(ut: generate_token(user.id))
      user.reload
      expect(user.notification_setting.email_mention_notifications).to be(false)
    end

    it "handles error properly" do
      expect { get email_subscriptions_unsubscribe_url }
        .to raise_error(ActiveRecord::RecordNotFound)
    end

    it "does not work if it is past the expiration date" do
      token = generate_token(user.id)
      Timecop.freeze(32.days.from_now) do
        get email_subscriptions_unsubscribe_url(ut: token)
        expect(response.body).to include("Token expired or invalid")
      end
    end
  end

  # RFC 8058: Gmail/Yahoo POST to the List-Unsubscribe URL with a
  # "List-Unsubscribe=One-Click" body and no CSRF token.
  describe "POST /email_subscriptions/unsubscribe" do
    around do |example|
      original = ActionController::Base.allow_forgery_protection
      ActionController::Base.allow_forgery_protection = true
      example.run
    ensure
      ActionController::Base.allow_forgery_protection = original
    end

    it "unsubscribes the user and returns 200 without a CSRF token", :aggregate_failures do
      post email_subscriptions_unsubscribe_path(ut: generate_token(user.id)),
           params: { "List-Unsubscribe" => "One-Click" }

      expect(response).to have_http_status(:ok)
      user.reload
      expect(user.notification_setting.email_mention_notifications).to be(false)
    end

    it "renders the expired notice for a stale token" do
      token = generate_token(user.id)
      Timecop.freeze(32.days.from_now) do
        post email_subscriptions_unsubscribe_path(ut: token),
             params: { "List-Unsubscribe" => "One-Click" }
        expect(response.body).to include("Token expired or invalid")
      end
    end
  end
end
